weights: ''
cfg: /content/yolov5/models/hub/yolov5s6.yaml
data: /content/drive/MyDrive/ColabNotebooks/AECVision/small_dataset/dataset_googlecollab_walls.yaml
hyp:
  lr0: 0.01
  lrf: 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.3
  cls_pw: 1.0
  obj: 0.7
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0
  hsv_s: 0
  hsv_v: 0
  degrees: 0.0
  translate: 0
  scale: 0
  shear: 0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.0
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
epochs: 300
batch_size: 20
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: /content/drive/MyDrive/ColabNotebooks/AECVision/train_results
name: traine_
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /content/drive/MyDrive/ColabNotebooks/AECVision/train_results/traine_
